// @/config/compact-page-structure-config.ts

import { RootContentStructure } from "@/app/@right/(_service)/(_types)/page-types";


export const COMPACT_CONTENT_STRUCTURE: RootContentStructure[] = [
  // Introduction section
  {
    id: "h2-1",
    tag: "h2",
    classification: "semantic",
    keywords: [
      // High-level prompting for keywords (kept explicit for consistency)
      "Generate 5-7 section-level keywords inherited by children",
    ],

    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",


    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 300,
      maxWords: 450,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-1-1",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 90,
          maxWords: 160,
          actualContent: "",
        },
      },
      {
        id: "p-1-2",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 70,
          maxWords: 130,
          actualContent: "",
        },
      },
      {
        id: "p-1-3",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 5,
          maxWords: 15,
          actualContent: "",
        },
      },
      {
        id: "blockquote-1-4",
        tag: "blockquote",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 25,
          maxWords: 45,
          actualContent: "",
        },
      },
      {
        id: "p-1-5",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 60,
          maxWords: 110,
          actualContent: "",
        },
      },
      {
        id: "ul-1-6",
        tag: "ul",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 40,
          maxWords: 70,
          actualContent: "",
        },
      },
    ],
  },

  // Main Content section
  {
    id: "h2-2",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords to guide h3/h4 children.",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 550,
      maxWords: 750,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-2-1",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 80,
          maxWords: 140,
          actualContent: "",
        },
      },
      {
        id: "p-2-2",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 5,
          maxWords: 15,
          actualContent: "",
        },
      },
      {
        id: "h3-2-3",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-2-3-1",
            tag: "p",
           keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 130,
              actualContent: "",
            },
          },
          {
            id: "ul-2-3-2",
            tag: "ul",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 50,
              maxWords: 85,
              actualContent: "",
            },
          },
          {
            id: "p-2-3-3",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 65,
              maxWords: 115,
              actualContent: "",
            },
          },
          {
            id: "code-2-3-4",
            tag: "code",
           keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 20,
              maxWords: 45,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-2-4",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 280,
          maxWords: 400,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-2-4-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",

        selfPrompt:"",additionalData: {
              minWords: 70,
              maxWords: 120,
              actualContent: "",
            },
          },
          {
            id: "table-2-4-2",
            tag: "table",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 90,
              maxWords: 150,
              actualContent: "",
            },
          },
          {
            id: "p-2-4-3",
            tag: "p",
           keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 5,
              maxWords: 15,
              actualContent: "",
            },
          },
          {
            id: "h4-2-4-4",
            tag: "h4",
           keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 130,
              maxWords: 200,
              actualContent: "",
            },
            realContentStructure: [
              {
                id: "p-2-4-4-1",
                tag: "p",
               keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 60,
                  maxWords: 105,
                  actualContent: "",
                },
              },
              {
                id: "ol-2-4-4-2",
                tag: "ol",
                keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 45,
                  maxWords: 75,
                  actualContent: "",
                },
              },
              {
                id: "blockquote-2-4-4-3",
                tag: "blockquote",
                keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 20,
                  maxWords: 40,
                  actualContent: "",
                },
              },
            ],
          },
        ],
      },
    ],
  },

  // FAQ section
  {
    id: "FAQ",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 FAQ-related keywords tied to user intent.",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

   designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 350,
      maxWords: 500,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-FAQ",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 70,
          maxWords: 120,
          actualContent: "",
        },
      },
      {
        id: "h3-FAQ-1",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 160,
          maxWords: 240,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-1-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 120,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-2",
        tag: "h3",
       keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 160,
          maxWords: 240,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-2-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 65,
              maxWords: 115,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-3",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 160,
          maxWords: 240,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-3-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 130,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },
];
