// @/config/appConfig.ts
// Comments in English: Single source of truth for SEO/PWA. Everything reads from here.

const site_url = "https://usavtopro.ru";

export const appConfig: AppConfig = {
  name: "USAUTO Путевые листы",
  short_name: "USAUTO ",
  description: "USAUTO Путевые листы, Управление коммерческим автопаркомОблачное решение комплексного управления коммерческим автомобильным парком. ",
  url: site_url,
  ogImage: `${site_url}/images/usautopro1.jpg`,

  // Next.js convention via app/manifest.ts
  manifest: "/manifest.webmanifest",

  lang: "ru",
  mailSupport: "support@aifa.dev",
  illustrations: {
    loading: {
      dark: "/_static/illustrations/idea-launch.svg",
      light: "/_static/illustrations/success.svg",
    },
  },
  startChatIllustration: "/app-config-images/logo.png",
  logo: "/app-config-images/logo.png",
  chatBrand: "Chat GPT",

  // Icons set for Metadata API and PWA
  icons: {
    faviconAny: "/favicon.ico",
    icon32: "/icons/icon-32.png",
    icon48: "/icons/icon-48.png",
    icon192: "/android-chrome-192x192.png",
    icon512: "/android-chrome-512x512.png",
    appleTouch: "/apple-touch-icon.png",
  },

  // PWA defaults
  pwa: {
    themeColor: "#ffffff",
    backgroundColor: "#ffffff",
    startUrl: "/",
    display: "standalone",
    scope: "/",
    orientation: "any",
  },

  // SEO and crawling
  seo: {
    indexing: "allow",
    sitemapUrl: `${site_url}/sitemap.xml`,
    disallowPaths: ["/admin", "/auth", "/login", "/register", "/chat", "/api", "/_next"],
    canonicalBase: site_url,
    locales: ["ru"],
    defaultLocale: "ru",
    social: {
      twitter: "@aifa_agi",
      github: "https://github.com/aifa-agi/aifa",
    },
  },

  // Open Graph / Twitter defaults
  og: {
    type: "website",
    locale: "ru_RU",
    siteName: "USAUTO ",
    imageWidth: 1200,
    imageHeight: 630,
  },

  // Per-page defaults (can be overridden by constructMetadata arguments)
  pageDefaults: {
    titleTemplate: "%s | USAUTO ",
    robotsIndex: true,
    robotsFollow: true,
  },

  messages: {
    loading: {
      title: "Загрузка...",
      subtitle: "Пожалуйста, подождите",
    },
  },
};

export type SupportedLang = "ru" | "en" | "es" | "fr" | "de" | "it";

export interface AppConfig {
  name: string;
  short_name: string;
  description: string;
  url: string;
  ogImage: string;
  manifest: string;
  mailSupport: string;
  lang: SupportedLang;
  illustrations: {
    loading: {
      dark: string;
      light: string;
    };
  };
  startChatIllustration: string;
  logo: string;
  chatBrand: string;
  icons: {
    faviconAny?: string;
    icon32?: string;
    icon48?: string;
    icon192: string;
    icon512: string;
    appleTouch?: string;
  };

  pwa: {
    themeColor: string;
    backgroundColor: string;
    startUrl: string;
    display: "fullscreen" | "standalone" | "minimal-ui" | "browser";
    scope?: string;
    orientation?: "any" | "portrait" | "landscape";
  };

  seo: {
    indexing: "allow" | "disallow";
    sitemapUrl?: string;
    disallowPaths?: string[];
    canonicalBase?: string;
    locales?: string[];
    defaultLocale?: string;
    social?: {
      twitter?: string;
      github?: string;
      linkedin?: string;
      facebook?: string;
    };
  };

  og?: {
    type?: "website" | "article" | "profile" | "video.other";
    locale?: string;
    siteName?: string;
    imageWidth?: number;
    imageHeight?: number;
  };

  pageDefaults?: {
    titleTemplate?: string;
    robotsIndex?: boolean;
    robotsFollow?: boolean;
  };

  messages?: {
    loading?: {
      title?: string;
      subtitle?: string;
    };
  };
}

// Last updated: 2025-10-04T22:33:43.981Z
// Generated by: app-config-persist-api
