// @/config/default-page-structure-config.ts

import { RootContentStructure } from "@/app/@right/(_service)/(_types)/page-types";

export const DEFAULT_CONTENT_STRUCTURE: RootContentStructure[] = [
  // Introduction section
  {
    id: "h2-1",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords that introduce the topic, establish context, and set the foundation for the entire page",
    ],
    taxonomy: "Guide | Section overview",
    attention: "Establish clear value and compelling context from the first sentence.",
    intent: "Introduce the topic comprehensively, communicate core value, and prepare readers for in-depth exploration.",
    audiences: "General business audience, decision-makers, and practitioners; level: beginner-to-intermediate.",
    selfPrompt:
      "Create an H2 introduction section that establishes the topic with clarity and impact. Frame the core message, state the value proposition, and set expectations for what follows. Use accessible language while maintaining authority. Naturally integrate the listed keywords without stuffing. Respect minWords/maxWords from additionalData. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 200,
      maxWords: 350,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-1-1",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 120,
          maxWords: 250,
          actualContent: "",
        },
      },
      {
        id: "p-1-2",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 80,
          maxWords: 180,
          actualContent: "",
        },
      },
      {
        id: "p-1-3",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 5,
          maxWords: 15,
          actualContent: "",
        },
      },
      {
        id: "blockquote-1-4",
        tag: "blockquote",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 25,
          maxWords: 50,
          actualContent: "",
        },
      },
    ],
  },

  // Technical Foundation section
  {
    id: "h2-2",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords focused on technical foundations, core concepts, and fundamental principles",
    ],
    taxonomy: "Guide | Technical foundation",
    attention: "Explain foundational concepts with precision and clarity.",
    intent: "Establish comprehensive technical foundations that readers can build upon throughout the page.",
    audiences: "Technical practitioners, developers, and implementers; level: intermediate-to-advanced.",
    selfPrompt:
      "Create an H2 section that establishes robust technical foundations with clear explanations, structured subsections, practical examples, and data. Use precise terminology while maintaining accessibility. Organize content for progressive understanding. Naturally integrate the listed keywords. Respect minWords/maxWords from additionalData. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 400,
      maxWords: 600,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-2-1",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 100,
          maxWords: 200,
          actualContent: "",
        },
      },
      {
        id: "h3-2-2",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-2-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
          {
            id: "p-2-2-2",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 90,
              maxWords: 180,
              actualContent: "",
            },
          },
          {
            id: "p-2-2-3",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 5,
              maxWords: 15,
              actualContent: "",
            },
          },
          {
            id: "table-2-2-4",
            tag: "table",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-2-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 100,
          maxWords: 200,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-2-3-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
          {
            id: "ul-2-3-2",
            tag: "ul",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 40,
              maxWords: 80,
              actualContent: "",
            },
          },
          {
            id: "code-2-3-3",
            tag: "code",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 20,
              maxWords: 50,
              actualContent: "",
            },
          },
          {
            id: "p-2-3-4",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 60,
              maxWords: 120,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // Implementation Process section
  {
    id: "h2-3",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords focused on implementation methodology, step-by-step processes, and practical execution",
    ],
    taxonomy: "Guide | Implementation section",
    attention: "Provide comprehensive, actionable implementation guidance with clear structure.",
    intent: "Guide readers through the complete implementation process with detailed steps, code examples, and nested subsections.",
    audiences: "Implementers, developers, and technical practitioners; level: intermediate-to-advanced.",
    selfPrompt:
      "Create an H2 section that provides comprehensive implementation guidance with clear methodology, step-by-step processes, nested subsections, code examples, and practical tips. Structure the content for easy follow-along and progressive complexity. Naturally integrate the listed keywords. Respect minWords/maxWords from additionalData. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 500,
      maxWords: 750,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-3-1",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 5,
          maxWords: 15,
          actualContent: "",
        },
      },
      {
        id: "p-3-2",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 110,
          maxWords: 220,
          actualContent: "",
        },
      },
      {
        id: "h3-3-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 350,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-3-3-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
          {
            id: "ol-3-3-2",
            tag: "ol",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 50,
              maxWords: 100,
              actualContent: "",
            },
          },
          {
            id: "h4-3-3-3",
            tag: "h4",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 200,
              actualContent: "",
            },
            realContentStructure: [
              {
                id: "p-3-3-3-1",
                tag: "p",
                 keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 75,
                  maxWords: 150,
                  actualContent: "",
                },
              },
              {
                id: "code-3-3-3-2",
                tag: "code",
                 keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 25,
                  maxWords: 60,
                  actualContent: "",
                },
              },
              {
                id: "p-3-3-3-3",
                tag: "p",
                 keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 65,
                  maxWords: 130,
                  actualContent: "",
                },
              },
            ],
          },
        ],
      },
      {
        id: "h3-3-4",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 150,
          maxWords: 250,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-3-4-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 95,
              maxWords: 190,
              actualContent: "",
            },
          },
          {
            id: "blockquote-3-4-2",
            tag: "blockquote",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 20,
              maxWords: 45,
              actualContent: "",
            },
          },
          {
            id: "ol-3-4-3",
            tag: "ol",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 60,
              maxWords: 120,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // Advanced Topics section
  {
    id: "h2-4",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords focused on advanced concepts, optimization, edge cases, and expert-level techniques",
    ],
    taxonomy: "Guide | Advanced topics",
    attention: "Provide expert-level guidance on advanced concepts and optimizations.",
    intent: "Cover advanced topics, optimizations, edge cases, and expert techniques for sophisticated users.",
    audiences: "Advanced practitioners, technical experts, and power users; level: advanced.",
    selfPrompt:
      "Create an H2 section that covers advanced topics with depth and sophistication. Include complex subsections, expert insights, optimization techniques, and edge-case handling. Use precise technical language while maintaining clarity. Naturally integrate the listed keywords. Respect minWords/maxWords from additionalData. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 450,
      maxWords: 650,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-4-1",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 100,
          maxWords: 200,
          actualContent: "",
        },
      },
      {
        id: "h3-4-2",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-4-2-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 5,
              maxWords: 15,
              actualContent: "",
            },
          },
          {
            id: "p-4-2-2",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 90,
              maxWords: 180,
              actualContent: "",
            },
          },
          {
            id: "p-4-2-3",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
          {
            id: "ul-4-2-4",
            tag: "ul",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 45,
              maxWords: 90,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-4-3",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 250,
          maxWords: 350,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-4-3-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "p-4-3-2",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
          {
            id: "ol-4-3-3",
            tag: "ol",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 55,
              maxWords: 110,
              actualContent: "",
            },
          },
          {
            id: "blockquote-4-3-4",
            tag: "blockquote",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 18,
              maxWords: 40,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // Monitoring and Maintenance section
  {
    id: "h2-5",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords focused on ongoing monitoring, maintenance practices, troubleshooting, and lifecycle management",
    ],
    taxonomy: "Guide | Operations and maintenance",
    attention: "Provide comprehensive guidance on ongoing operations and maintenance.",
    intent: "Cover monitoring strategies, maintenance best practices, troubleshooting, and lifecycle management.",
    audiences: "Operations teams, maintainers, and long-term practitioners; level: intermediate-to-advanced.",
    selfPrompt:
      "Create an H2 section that covers ongoing monitoring, maintenance practices, troubleshooting approaches, and lifecycle management. Include practical checklists and detailed subsections. Use operational language while maintaining technical accuracy. Naturally integrate the listed keywords. Respect minWords/maxWords from additionalData. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 400,
      maxWords: 550,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-5-1",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 105,
          maxWords: 210,
          actualContent: "",
        },
      },
      {
        id: "p-5-2",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 5,
          maxWords: 15,
          actualContent: "",
        },
      },
      {
        id: "h3-5-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 150,
          maxWords: 250,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-5-3-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
          {
            id: "ul-5-3-2",
            tag: "ul",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 40,
              maxWords: 80,
              actualContent: "",
            },
          },
          {
            id: "p-5-3-3",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // FAQ section
  {
    id: "FAQ",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 FAQ-related keywords tied to common user questions, concerns, and decision-making blockers",
    ],
    taxonomy: "FAQ | Q&A section",
    attention: "Anticipate and answer the most pressing user questions comprehensively.",
    intent: "Address common questions with clear, helpful answers across beginner to advanced levels.",
    audiences: "Prospects, users, decision-makers, and technical stakeholders; level: beginner-to-advanced.",
    selfPrompt:
      "This FAQ H2 section is designed for generating relevant questions and answers. Adopt the user's perspective by analyzing existing content and understanding the target audience. Generate six high-impact questions that would be most interesting and useful within the context of the topic, covering beginner, intermediate, and advanced concerns. Organize each question under an H3 heading with a well-crafted answer. Avoid repeating content from other sections. Respect min/max words per element. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 450,
      maxWords: 600,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-FAQ",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 95,
          maxWords: 190,
          actualContent: "",
        },
      },
      {
        id: "h3-FAQ-1",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-1-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 150,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-2",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 150,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-3-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 150,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-4",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-4-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 150,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-5",
        tag: "h3",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-5-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 150,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-6",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-6-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 75,
              maxWords: 150,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // Summary section
  {
    id: "h2-7",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 5-7 section-level keywords focused on synthesis, summary, key takeaways, comparisons, and calls-to-action",
    ],
    taxonomy: "Guide | Summary and conclusion",
    attention: "Synthesize key points comprehensively and guide readers toward next steps.",
    intent: "Summarize the main insights, provide comparative data, highlight key takeaways, and suggest clear next actions.",
    audiences: "All readers; level: general-to-intermediate.",
    selfPrompt:
      "Create an H2 summary section that synthesizes the key points from the entire page, presents comparative data in tables, reinforces the main value proposition with expert quotes, and suggests clear next steps or calls-to-action. Be comprehensive yet concise. Naturally integrate the listed keywords. Respect minWords/maxWords from additionalData. Generate the necessary content here.",
    designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 300,
      maxWords: 450,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-7-1",
        tag: "p",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 60,
          maxWords: 240,
          actualContent: "",
        },
      },
      {
        id: "p-7-2",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 100,
          maxWords: 200,
          actualContent: "",
        },
      },
      {
        id: "table-6-2-2",
        tag: "table",
        keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
      },
      {
        id: "ul-7-3",
        tag: "ul",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 60,
          maxWords: 120,
          actualContent: "",
        },
      },
      {
        id: "p-7-4",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 80,
          maxWords: 160,
          actualContent: "",
        },
      },
      {
        id: "blockquote-7-5",
        tag: "blockquote",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 15,
          maxWords: 35,
          actualContent: "",
        },
      },
    ],
  },
];
