// @/config/long-read-page-structure-config.ts

import { RootContentStructure } from "@/app/@right/(_service)/(_types)/page-types";

export const LONG_READ_CONTENT_STRUCTURE: RootContentStructure[] = [
  // 1. Comprehensive Introduction section
  {
    id: "h2-1",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords that comprehensively introduce the topic, establish deep context, historical background, and set comprehensive expectations for an in-depth exploration",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 500,
      maxWords: 750,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-1-1",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 150,
          maxWords: 280,
          actualContent: "",
        },
      },
      {
        id: "p-1-2",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 120,
          maxWords: 240,
          actualContent: "",
        },
      },
      {
        id: "p-1-3",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 100,
          maxWords: 200,
          actualContent: "",
        },
      },
      {
        id: "p-1-4",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 5,
          maxWords: 15,
          actualContent: "",
        },
      },
      {
        id: "blockquote-1-5",
        tag: "blockquote",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 30,
          maxWords: 60,
          actualContent: "",
        },
      },
      {
        id: "p-1-6",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 90,
          maxWords: 180,
          actualContent: "",
        },
      },
    ],
  },

  // 2. Foundational Concepts and Principles section
  {
    id: "h2-2",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on foundational concepts, core principles, theoretical frameworks, and fundamental understanding",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 600,
      maxWords: 850,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-2-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 130,
          maxWords: 260,
          actualContent: "",
        },
      },
      {
        id: "h3-2-2",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 350,
          maxWords: 500,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-2-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "p-2-2-2",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
          {
            id: "ul-2-2-3",
            tag: "ul",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 60,
              maxWords: 120,
              actualContent: "",
            },
          },
          {
            id: "p-2-2-4",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 5,
              maxWords: 15,
              actualContent: "",
            },
          },
          {
            id: "table-2-2-5",
            tag: "table",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 220,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-2-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 250,
          maxWords: 350,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-2-3-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
          {
            id: "ol-2-3-2",
            tag: "ol",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
          {
            id: "blockquote-2-3-3",
            tag: "blockquote",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 25,
              maxWords: 50,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 3. Technical Architecture and Design section
  {
    id: "h2-3",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on technical architecture, system design, structural components, design patterns, and architectural decisions",
    ],
   
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 700,
      maxWords: 950,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-3-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 140,
          maxWords: 280,
          actualContent: "",
        },
      },
      {
        id: "h3-3-2",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 400,
          maxWords: 550,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-3-2-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 240,
              actualContent: "",
            },
          },
          {
            id: "code-3-2-2",
            tag: "code",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 40,
              maxWords: 80,
              actualContent: "",
            },
          },
          {
            id: "p-3-2-3",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
          {
            id: "h4-3-2-4",
            tag: "h4",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 250,
              maxWords: 400,
              actualContent: "",
            },
            realContentStructure: [
              {
                id: "p-3-2-4-1",
                tag: "p",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 90,
                  maxWords: 180,
                  actualContent: "",
                },
              },
              {
                id: "ul-3-2-4-2",
                tag: "ul",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 60,
                  maxWords: 120,
                  actualContent: "",
                },
              },
              {
                id: "code-3-2-4-3",
                tag: "code",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 30,
                  maxWords: 70,
                  actualContent: "",
                },
              },
            ],
          },
          {
            id: "table-3-2-5",
            tag: "table",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-3-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 300,
          maxWords: 400,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-3-3-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "ol-3-3-2",
            tag: "ol",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
          {
            id: "blockquote-3-3-3",
            tag: "blockquote",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 25,
              maxWords: 50,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 4. Implementation Methodology and Best Practices section
  {
    id: "h2-4",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on implementation methodology, step-by-step procedures, development workflow, best practices, and practical execution strategies",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 800,
      maxWords: 1100,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-4-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 150,
          maxWords: 300,
          actualContent: "",
        },
      },
      {
        id: "h3-4-2",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 350,
          maxWords: 500,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-4-2-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 240,
              actualContent: "",
            },
          },
          {
            id: "ul-4-2-2",
            tag: "ul",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
          {
            id: "p-4-2-3",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
          {
            id: "code-4-2-4",
            tag: "code",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 35,
              maxWords: 70,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-4-3",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 450,
          maxWords: 600,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-4-3-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
          {
            id: "ol-4-3-2",
            tag: "ol",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
          {
            id: "h4-4-3-3",
            tag: "h4",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 300,
              maxWords: 450,
              actualContent: "",
            },
            realContentStructure: [
              {
                id: "p-4-3-3-1",
                tag: "p",
                 keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 110,
                  maxWords: 220,
                  actualContent: "",
                },
              },
              {
                id: "code-4-3-3-2",
                tag: "code",
                 keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 50,
                  maxWords: 100,
                  actualContent: "",
                },
              },
              {
                id: "ul-4-3-3-3",
                tag: "ul",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 60,
                  maxWords: 120,
                  actualContent: "",
                },
              },
              {
                id: "p-4-3-3-4",
                tag: "p",
                 keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 80,
                  maxWords: 160,
                  actualContent: "",
                },
              },
            ],
          },
          {
            id: "h4-4-3-4",
            tag: "h4",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 200,
              maxWords: 350,
              actualContent: "",
            },
            realContentStructure: [
              {
                id: "p-4-3-4-1",
                tag: "p",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 100,
                  maxWords: 200,
                  actualContent: "",
                },
              },
              {
                id: "code-4-3-4-2",
                tag: "code",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 40,
                  maxWords: 80,
                  actualContent: "",
                },
              },
              {
                id: "blockquote-4-3-4-3",
                tag: "blockquote",
                  keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
                  minWords: 20,
                  maxWords: 45,
                  actualContent: "",
                },
              },
            ],
          },
        ],
      },
    ],
  },

  // 5. Performance Optimization and Scalability section
  {
    id: "h2-5",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on performance optimization, scalability strategies, efficiency improvements, resource management, and performance monitoring",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 650,
      maxWords: 900,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-5-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 130,
          maxWords: 260,
          actualContent: "",
        },
      },
      {
        id: "h3-5-2",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 400,
          maxWords: 550,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-5-2-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "code-5-2-2",
            tag: "code",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 45,
              maxWords: 90,
              actualContent: "",
            },
          },
          {
            id: "table-5-2-3",
            tag: "table",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 240,
              actualContent: "",
            },
          },
          {
            id: "p-5-2-4",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 90,
              maxWords: 180,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-5-3",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 350,
          maxWords: 450,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-5-3-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 240,
              actualContent: "",
            },
          },
          {
            id: "ul-5-3-2",
            tag: "ul",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
          {
            id: "p-5-3-3",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 6. Security, Compliance, and Risk Management section
  {
    id: "h2-6",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on security practices, compliance requirements, risk mitigation, threat modeling, and security architecture",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 600,
      maxWords: 850,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-6-1",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
          minWords: 140,
          maxWords: 280,
          actualContent: "",
        },
      },
      {
        id: "h3-6-2",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 350,
          maxWords: 500,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-6-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "table-6-2-2",
            tag: "table",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 130,
              maxWords: 260,
              actualContent: "",
            },
          },
          {
            id: "code-6-2-3",
            tag: "code",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 40,
              maxWords: 80,
              actualContent: "",
            },
          },
          {
            id: "ul-6-2-4",
            tag: "ul",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-6-3",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 300,
          maxWords: 400,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-6-3-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 240,
              actualContent: "",
            },
          },
          {
            id: "ol-6-3-2",
            tag: "ol",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
          {
            id: "blockquote-6-3-3",
            tag: "blockquote",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 25,
              maxWords: 50,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 7. Real-World Case Studies and Applications section
  {
    id: "h2-7",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on real-world applications, case studies, industry examples, success stories, and practical lessons learned",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 550,
      maxWords: 750,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-7-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 120,
          maxWords: 240,
          actualContent: "",
        },
      },
      {
        id: "h3-7-2",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 350,
          maxWords: 500,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-7-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 100,
              maxWords: 200,
              actualContent: "",
            },
          },
          {
            id: "p-7-2-2",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "table-7-2-3",
            tag: "table",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 130,
              maxWords: 260,
              actualContent: "",
            },
          },
          {
            id: "blockquote-7-2-4",
            tag: "blockquote",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 25,
              maxWords: 50,
              actualContent: "",
            },
          },
          {
            id: "ul-7-2-5",
            tag: "ul",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 60,
              maxWords: 120,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-7-3",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-7-3-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "p-7-3-2",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 90,
              maxWords: 180,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 8. Advanced Topics and Future Trends section
  {
    id: "h2-8",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on advanced topics, emerging trends, future developments, innovation horizons, and strategic evolution",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 550,
      maxWords: 800,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-8-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 130,
          maxWords: 260,
          actualContent: "",
        },
      },
      {
        id: "h3-8-2",
        tag: "h3",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 350,
          maxWords: 500,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-8-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 120,
              maxWords: 240,
              actualContent: "",
            },
          },
          {
            id: "p-8-2-2",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "ul-8-2-3",
            tag: "ul",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 70,
              maxWords: 140,
              actualContent: "",
            },
          },
          {
            id: "blockquote-8-2-4",
            tag: "blockquote",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 30,
              maxWords: 60,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-8-3",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 200,
          maxWords: 300,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-8-3-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 110,
              maxWords: 220,
              actualContent: "",
            },
          },
          {
            id: "ol-8-3-2",
            tag: "ol",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 9. FAQ section
  {
    id: "FAQ",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 FAQ-related keywords tied to comprehensive user questions across beginner, intermediate, advanced, and specialized concerns",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 600,
      maxWords: 850,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-FAQ",
        tag: "p",
         keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 110,
          maxWords: 220,
          actualContent: "",
        },
      },
      {
        id: "h3-FAQ-1",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-1-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-2",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-2-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
              minWords: 80,
              maxWords: 160,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-3",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-3-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-4",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-4-1",
            tag: "p",
             keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 90,
              maxWords: 180,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-5",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-5-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-6",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-6-1",
            tag: "p",
            keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
         additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-7",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-7-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
        ],
      },
      {
        id: "h3-FAQ-8",
        tag: "h3",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 320,
          actualContent: "",
        },
        realContentStructure: [
          {
            id: "p-FAQ-8-1",
            tag: "p",
              keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
              minWords: 85,
              maxWords: 170,
              actualContent: "",
            },
          },
        ],
      },
    ],
  },

  // 10. Comprehensive Summary and Next Steps section
  {
    id: "h2-9",
    tag: "h2",
    classification: "semantic",
    keywords: [
      "Generate 6-8 section-level keywords focused on synthesis, comprehensive summary, key insights, actionable takeaways, recommended actions, and strategic next steps",
    ],
    
    taxonomy: "",
    attention: "",
    intent: "",
    audiences: "",
    selfPrompt:"",
    writingStyle:"",
  contentFormat:"",
  customRequirements:"",

  designDescription: "",
    connectedDesignSectionId: "",
    additionalData: {
      minWords: 500,
      maxWords: 750,
      actualContent: "",
    },
    realContentStructure: [
      {
        id: "p-9-1",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 120,
          maxWords: 240,
          actualContent: "",
        },
      },
      {
        id: "p-9-2",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 100,
          maxWords: 200,
          actualContent: "",
        },
      },
      {
        id: "table-9-3",
        tag: "table",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 220,
          maxWords: 350,
          actualContent: "",
        },
      },
      {
        id: "ul-9-4",
        tag: "ul",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 90,
          maxWords: 180,
          actualContent: "",
        },
      },
      {
        id: "p-9-5",
        tag: "p",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 130,
          maxWords: 260,
          actualContent: "",
        },
      },
      {
        id: "blockquote-9-6",
        tag: "blockquote",
          keywords: [],
        taxonomy: "",
        attention: "",
        intent: "",
        audiences: "",
        selfPrompt:"",
        additionalData: {
          minWords: 25,
          maxWords: 50,
          actualContent: "",
        },
      },
    ],
  },
];